### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by Asherlam** [ciarancrocker/sgs_bot#22]
```
(node:10604) UnhandledPromiseRejectionWarning: error: relation "channels" does not exist
    at Connection.parseE (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:604:13)
    at Connection.parseMessage (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:403:19)
    at Socket.<anonymous> (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:10604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10604) UnhandledPromiseRejectionWarning: error: relation "channels" does not exist
    at Connection.parseE (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:604:13)
    at Connection.parseMessage (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:403:19)
    at Socket.<anonymous> (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:10604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10604) UnhandledPromiseRejectionWarning: error: relation "channels" does not exist
    at Connection.parseE (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:604:13)
    at Connection.parseMessage (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:403:19)
    at Socket.<anonymous> (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:10604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10604) UnhandledPromiseRejectionWarning: error: relation "channels" does not exist
    at Connection.parseE (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:604:13)
    at Connection.parseMessage (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:403:19)
    at Socket.<anonymous> (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:10604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:10604) UnhandledPromiseRejectionWarning: error: relation "channels" does not exist
    at Connection.parseE (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:604:13)
    at Connection.parseMessage (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:403:19)
    at Socket.<anonymous> (C:\Users\Lam'Family\Desktop\omnium-develop\node_modules\pg\lib\connection.js:123:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:10604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)```

**Comment by ciarancrocker** [comment]
This error is coming from Postgres, as it can't find your database. I've seen this happen when you try to use mixed case when naming the database. Try creating the database with a lowercase only name.

**Comment by ciarancrocker** [comment]
Ok, so I was responding to the initial version of your issue. For future reference, please avoid changing the text of an issue to a different issue; instead close the original issue and open a new one.

Have you imported the Postgres schema from the provided file, as is referenced in the README?

**Comment by Asherlam** [comment]
![未命名](https://user-images.githubusercontent.com/35485292/73148522-c2f29900-40f7-11ea-8e70-d76d609a7f90.png)

**Comment by ciarancrocker** [comment]
Your screenshot does not show anything regarding the tables in the database. Please ensure you have imported the database schema from the file at https://github.com/ciarancrocker/omnium/blob/develop/psql_schema.psql.

**Comment by Asherlam** [comment]
May I ask how to import the database schema, Because I can't.
![2](https://user-images.githubusercontent.com/35485292/73324160-fadb1700-4284-11ea-86ce-87457878866c.png)

![1](https://user-images.githubusercontent.com/35485292/73324129-d97a2b00-4284-11ea-925f-ea3e18c13619.png)

**Comment by ciarancrocker** [comment]
I don't use pgAdmin. The relevant part of the postgres documentation is here: https://www.postgresql.org/docs/current/backup-dump.html#BACKUP-DUMP-RESTORE

**Comment by Asherlam** [comment]
Ok! Thanks a lot, I can run it perfectly. But where are the command for  
- Automatic channel renaming
- Burst channels

**Comment by ciarancrocker** [comment]
Those 2 features don't really have any commands for configuration, rather you set them up in the `channels` table in Postgres, which is what is read by the channel handler to manage both the renaming of channels and also creation/deletion of temporary channels.

There is one hard-coded thing that you may want to change, which is the template string used to name channels here: https://github.com/ciarancrocker/omnium/blob/develop/event_handlers/channel_handler.js#L108.

When setting up the channels table, simply insert a row for each permanent channel into the table with it's base name, channel ID and a value for ordering it, ensuring you set the column `temporary` to `false`.
